CREATE TABLE `uom_setting` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_by` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
  `updated_by` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `updated_date` TIMESTAMP NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `active_ind` TINYINT(1) NULL DEFAULT 1,
  `uom` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
  `description` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
  `uom_group` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
  `remark` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE SEQUENCE seq_uom_setting
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;